### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by phys1cs27** [Linaqruf/kohya-trainer#101]
image does not have tags / メタデータにタグがありません: 1 (3)
image does not have tags / メタデータにタグがありません: 1
image does not have tags / メタデータにタグがありません: 1 (2)
image does not have tags / メタデータにタグがありません: 1 (11)
image does not have tags / メタデータにタグがありません: 1 (12)
image does not have tags / メタデータにタグがありません: 1 (9)
image does not have tags / メタデータにタグがありません: 1 (5)
image does not have tags / メタデータにタグがありません: 1 (4)
image does not have tags / メタデータにタグがありません: 1 (10)
image does not have tags / メタデータにタグがありません: 1 (6)
image does not have tags / メタデータにタグがありません: 1 (8)
100% 42/42 [00:00<00:00, 2448.17it/s]
writing metadata: /content/drive/MyDrive/training_dir/meta_clean.json
done!
+--------------------------+---------------------------------------------------------------+
| Hyperparameter           | Value                                                         |
+--------------------------+---------------------------------------------------------------+
| mode                     | LoRA                                                          |
| use_dreambooth_method    | False                                                         |
| lowram                   | True                                                          |
| v2                       | False                                                         |
| v_parameterization       | False                                                         |
| project_name             | RachelGardnerLora                                             |
| modelPath                | /content/pretrained_model/anything-v3-fp32-pruned.safetensors |
| vaePath                  | /content/vae/anime.vae.pt                                     |
| train_data_dir           | /content/training_dir/train_data                              |
| meta_lat                 | /content/drive/MyDrive/training_dir/meta_lat.json             |
| output_dir               | /content/drive/MyDrive/training_dir/output                    |
| network_dim              | 128                                                           |
| network_alpha            | 128                                                           |
| network_weights          | False                                                         |
| unet_lr                  | 0.0001                                                        |
| text_encoder_lr          | 5e-05                                                         |
| optimizer_type           | AdamW8bit                                                     |
| optimizer_args           | False                                                         |
| learning_rate            | 2e-06                                                         |
| lr_scheduler             | constant                                                      |
| lr_warmup_steps          | 250                                                           |
| lr_scheduler_args        | 1                                                             |
| keep_tokens              | 1                                                             |
| dataset_repeats          | 10                                                            |
| resolution               | 512                                                           |
| noise_offset             | 0                                                             |
| mixed_precision          | fp16                                                          |
| save_precision           | fp16                                                          |
| save_n_epochs_type       | save_n_epoch_ratio                                            |
| save_n_epochs_type_value | 3                                                             |
| save_model_as            | safetensors                                                   |
| train_batch_size         | 4                                                             |
| max_train_type           | max_train_epochs                                              |
| max_train_type_value     | 30                                                            |
| clip_skip                | 2                                                             |
| logging_dir              | /content/training_dir/logs                                    |
| additional_argument      | --shuffle_caption --xformers                                  |
+--------------------------+---------------------------------------------------------------+
2023-02-28 07:07:57.184840: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-28 07:07:58.160532: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-28 07:07:58.160668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-28 07:07:58.160709: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-28 07:08:01.817010: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-28 07:08:02.499361: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-28 07:08:02.499466: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-28 07:08:02.499488: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
update token length: 225
Train with captions.
loading existing metadata: /content/drive/MyDrive/training_dir/meta_lat.json
Traceback (most recent call last):
  File "/content/kohya-trainer/train_network.py", line 507, in <module>
    train(args)
  File "/content/kohya-trainer/train_network.py", line 69, in train
    train_dataset = FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 842, in __init__
    assert len(abs_path) >= 1, f"no image / 画像がありません: {image_key}"
AssertionError: no image / 画像がありません: 1 (7)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya-trainer/train_network.py', '--output_name=RachelGardnerLora', '--pretrained_model_name_or_path=/content/pretrained_model/anything-v3-fp32-pruned.safetensors', '--vae=/content/vae/anime.vae.pt', '--train_data_dir=/content/training_dir/train_data', '--in_json=/content/drive/MyDrive/training_dir/meta_lat.json', '--output_dir=/content/drive/MyDrive/training_dir/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--unet_lr=0.0001', '--text_encoder_lr=5e-05', '--optimizer_type=AdamW8bit', '--learning_rate=2e-06', '--lr_scheduler=constant', '--lr_warmup_steps=250', '--dataset_repeats=10', '--resolution=512', '--keep_tokens=1', '--lowram', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--train_batch_size=4', '--max_token_length=225', '--max_train_epochs=30', '--clip_skip=2', '--logging_dir=/content/training_dir/logs', '--log_prefix=RachelGardnerLora', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

**Comment by phys1cs27** [comment]
![image](https://user-images.githubusercontent.com/95995512/221782434-621295ff-fd79-408f-a314-a2394568a7d0.png)
Solved, just off this...
