### ISSUE TITLE
Load StableDiffusion checkpoint error

### ISSUE THREAD

**Issue by cerarslan** [Linaqruf/kohya-trainer#102]
When I try to dowloand model from Civitai, it gives me this error. Btw model download successfully to pretrained_model folder. Thank you for all effort sir. I appereciate to you!

Fast Kohya Trainer NEW | Easy 1-click LoRA & Native Training
Link: https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/fast-kohya-trainer.ipynb

load StableDiffusion checkpoint
Traceback (most recent call last):
  File "/content/kohya-trainer/train_network.py", line 507, in <module>
    train(args)
  File "/content/kohya-trainer/train_network.py", line 96, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "/content/kohya-trainer/library/train_util.py", line 1860, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path)
  File "/content/kohya-trainer/library/model_util.py", line 869, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/kohya-trainer/library/model_util.py", line 846, in load_checkpoint_with_text_encoder_conversion
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'O'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya-trainer/train_network.py', '--output_name=evalora768', '--pretrained_model_name_or_path=/content/pretrained_model/13259', '--vae=/content/vae/none', '--train_data_dir=/content/drive/MyDrive/eva768', '--reg_data_dir=/content/drive/MyDrive/reg_data', '--output_dir=/content/drive/MyDrive/training_dir/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--unet_lr=0.0001', '--text_encoder_lr=5e-05', '--optimizer_type=AdamW8bit', '--learning_rate=2e-06', '--lr_scheduler=constant', '--lr_warmup_steps=250', '--resolution=768', '--enable_bucket', '--min_bucket_reso=320', '--max_bucket_reso=1280', '--caption_extension=.txt', '--cache_latents', '--prior_loss_weight=1.0', '--lowram', '--noise_offset=0.1', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--train_batch_size=6', '--max_token_length=225', '--max_train_epochs=20', '--clip_skip=2', '--logging_dir=/content/training_dir/logs', '--log_prefix=evalora768', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

**Comment by Linaqruf** [comment]
Hi, for Civitai you need to specify `modelName`
