### ISSUE TITLE
issue with fast kohya trainer colab

### ISSUE THREAD

**Issue by faisalhr1997** [Linaqruf/kohya-trainer#104]
exception occurs in loading vae: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like /content/vae/none is not the path to a directory containing a file named diffusion_pytorch_model.bin or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
retry with subfolder='vae'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/modeling_utils.py", line 605, in _get_model_file
    model_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/vae/none'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/kohya-trainer/library/model_util.py", line 1096, in load_vae
    vae = AutoencoderKL.from_pretrained(vae_id, subfolder=None, torch_dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/modeling_utils.py", line 453, in from_pretrained
    model_file = cls._get_model_file(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/modeling_utils.py", line 647, in _get_model_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like /content/vae/none is not the path to a directory containing a file named diffusion_pytorch_model.bin or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/modeling_utils.py", line 605, in _get_model_file
    model_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/vae/none'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/kohya-trainer/train_network.py", line 507, in <module>
    train(args)
  File "/content/kohya-trainer/train_network.py", line 96, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "/content/kohya-trainer/library/train_util.py", line 1875, in load_target_model
    vae = model_util.load_vae(args.vae, weight_dtype)
  File "/content/kohya-trainer/library/model_util.py", line 1100, in load_vae
    vae = AutoencoderKL.from_pretrained(vae_id, subfolder="vae", torch_dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/modeling_utils.py", line 453, in from_pretrained
    model_file = cls._get_model_file(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/modeling_utils.py", line 647, in _get_model_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like /content/vae/none is not the path to a directory containing a file named diffusion_pytorch_model.bin or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya-trainer/train_network.py', '--v2', '--v_parameterization', '--output_name=faisalhr', '--pretrained_model_name_or_path=/content/pretrained_model/illuminatiDiffusionV1_v11.safetensors', '--vae=/content/vae/none', '--train_data_dir=/content/training_dir/train_data', '--in_json=/content/drive/MyDrive/training_dir/meta_lat.json', '--output_dir=/content/drive/MyDrive/training_dir/output', '--network_dim=1', '--network_alpha=1', '--network_module=networks.lora', '--unet_lr=0.001', '--text_encoder_lr=5e-05', '--optimizer_type=DAdaptation', '--learning_rate=2e-06', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=250', '--lr_scheduler_num_cycles=1', '--dataset_repeats=1', '--resolution=768', '--keep_tokens=1', '--lowram', '--noise_offset=0.1', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--train_batch_size=4', '--max_token_length=225', '--max_train_epochs=20', '--logging_dir=/content/training_dir/logs', '--log_prefix=faisalhr', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

**Comment by Linaqruf** [comment]
Maybe late but the issue is in this args `--vae=/content/vae/none`

I realize that notebook need to bake vae to train, i'll fix it later
