### ISSUE TITLE
Errors in 4.4, Finetuning notebook does not run

### ISSUE THREAD

**Issue by Taikakim** [Linaqruf/kohya-trainer#106]
I'm on Colab Pro, T4. All the images seem to be processed and captioned fine, etc in the previous steps. 

```
+-------------------------------+-----------------------------------------------------------------+
| Hyperparameter                | Value                                                           |
+-------------------------------+-----------------------------------------------------------------+
| v2                            | True                                                            |
| v_parameterization            | False                                                           |
| project_name                  | Quorrv2-768                                                     |
| pretrained_model_name_or_path | /content/pretrained_model/stable-diffusion-2-1-768v.safetensors |
| vae                           | /content/vae/stablediffusion.vae.pt                             |
| train_data_dir                | /content/drive/MyDrive/LoRA/train_data                          |
| in_json                       | /content/LoRA/meta_lat.json                                     |
| output_dir                    | /content/drive/MyDrive/LoRA/output                              |
| resume_path                   | False                                                           |
+-------------------------------+-----------------------------------------------------------------+
+--------------------------------+-------+
| Hyperparameter                 | Value |
+--------------------------------+-------+
| dataset_repeats                | 10    |
| resolution                     | 768   |
| caption_dropout_rate           | 0     |
| tag_dropout_rate               | 0     |
| caption_dropout_every_n_epochs | 0     |
+--------------------------------+-------+
+-------------------+---------------+
| Hyperparameter    | Value         |
+-------------------+---------------+
| network_dim       | 128           |
| network_alpha     | 128           |
| network_module    | networks.lora |
| network_weight    | False         |
| optimizer_type    | AdamW8bit     |
| optimizer_args    | False         |
| unet_lr           | 0.0001        |
| text_encoder_lr   | 5e-05         |
| lr_scheduler      | constant      |
| lr_warmup_steps   | 0             |
| lr_scheduler_args | 1             |
+-------------------+---------------+
+-----------------------------+------------------------------+
| Hyperparameter              | Value                        |
+-----------------------------+------------------------------+
| lowram                      | True                         |
| noise_offset                | 0.1                          |
| max_train_type              | max_train_epochs             |
| max_train_type_value        | 20                           |
| train_batch_size            | 6                            |
| mixed_precision             | fp16                         |
| save_precision              | fp16                         |
| save_n_epochs_type          | save_n_epoch_ratio           |
| save_n_epochs_type_value    | 3                            |
| save_model_as               | safetensors                  |
| max_token_length            | 225                          |
| clip_skip                   | 2                            |
| gradient_checkpointing      | False                        |
| gradient_accumulation_steps | 1                            |
| seed                        | 303                          |
| logging_dir                 | /content/LoRA/logs           |
| additional_argument         | --shuffle_caption --xformers |
+-----------------------------+------------------------------+
2023-03-01 13:38:09.391162: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-01 13:38:10.472701: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-01 13:38:10.472896: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-01 13:38:10.472926: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-01 13:38:14.808393: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-01 13:38:15.727614: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-01 13:38:15.727733: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-01 13:38:15.727753: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
update token length: 225
Train with captions.
loading existing metadata: /content/LoRA/meta_lat.json
Traceback (most recent call last):
  File "train_network.py", line 507, in <module>
    train(args)
  File "train_network.py", line 69, in train
    train_dataset = FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 842, in __init__
    assert len(abs_path) >= 1, f"no image / 画像がありません: {image_key}"
AssertionError: no image / 画像がありません: blutartdolomite31
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--v2', '--output_name=Quorrv2-768', '--pretrained_model_name_or_path.....
```

**Comment by Taikakim** [comment]
I tried also v1.5 with 512px pics (those were 1024px I fed into V2)

```
2023-03-02 09:21:03.786207: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-02 09:21:04.648498: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-02 09:21:04.648610: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-02 09:21:04.648630: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-02 09:21:07.462740: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-02 09:21:08.178368: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-02 09:21:08.178484: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-02 09:21:08.178504: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 29.1MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 23.4MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 183kB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 468kB/s]
update token length: 225
Train with captions.
loading existing metadata: /content/LoRA/meta_lat.json
Traceback (most recent call last):
  File "train_network.py", line 507, in <module>
    train(args)
  File "train_network.py", line 69, in train
    train_dataset = FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 842, in __init__
    assert len(abs_path) >= 1, f"no image / 画像がありません: {image_key}"
AssertionError: no image / 画像がありません: blutartdolomite1
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--output_name=Quorrv15-512', '--pretrained_model_name_or_path=/content/pretrained_model/Stable-Diffusion-v1-5.safetensors', '--vae=/content/vae/stablediffusion.vae.pt', '--train_data_dir=/content/drive/MyDrive/LoRA/train_data', '--in_json=/content/LoRA/meta_lat.json', '--output_dir=/content/drive/MyDrive/LoRA/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--learning_rate=0.0001', '--unet_lr=0.0001', '--text_encoder_lr=5e-05', '--lr_scheduler=constant', '--dataset_repeats=10', '--resolution=1024', '--lowram', '--noise_offset=0.1', '--train_batch_size=6', '--max_train_epochs=20', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=ckpt', '--max_token_length=225', '--seed=303', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/LoRA/logs', '--log_prefix=Quorrv15-512', '--shuffle_caption', '--xformers']' returned non-zero exit status 1
```

**Comment by Taikakim** [comment]
Also, I'm wondering, in cell 4.4 for the model_dir  variable, by default when the notebook is opened, the Anything Diffusion model is selected. But at this point we are encoding latents, shouldn't a VAE  be used? The cell seems to work both ways.

**Comment by Taikakim** [comment]
Hmm, I realize I skipped the tagging cell, now that I run it, I get past those errors.

**Comment by Taikakim** [comment]
OK,now both V2 and 1.5 seem to work, I think the issue was also with some of the directories, when I had specified Gdrive folders for the JSON files. I reverted everything to default in the instance local /content, and it seemed to solve the issues.
