### ISSUE TITLE
Finetune issue

### ISSUE THREAD

**Issue by Gvaroo** [Linaqruf/kohya-trainer#110]
It was working yesterday, but for some reason today I got this error. same setting..

Traceback (most recent call last):
  File "train_network.py", line 20, in <module>
    import library.config_util as config_util
  File "/content/kohya-trainer/library/config_util.py", line 113, in <module>
    class ConfigSanitizer:
  File "/content/kohya-trainer/library/config_util.py", line 116, in ConfigSanitizer
    def __validate_and_convert_twodim(klass, value: Sequence) -> Tuple:
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 201, in __init__
    raise TypeError("Input must be callable")
TypeError: Input must be callable
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--output_name=dehya', '--pretrained_model_name_or_path=/content/pretrained_model/Animefull-final-pruned.ckpt', '--vae=/content/vae/waifudiffusion.vae.pt', '--train_data_dir=/content/LoRA/train_data', '--in_json=/content/LoRA/meta_lat.json', '--output_dir=/content/LoRA/output', '--network_dim=32', '--network_alpha=32.0', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--learning_rate=0.0001', '--unet_lr=0.0001', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=1', '--dataset_repeats=7', '--resolution=1024', '--keep_tokens=1', '--lowram', '--noise_offset=0.1', '--train_batch_size=1', '--max_train_epochs=7', '--mixed_precision=no', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--max_token_length=225', '--seed=23', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/LoRA/logs', '--log_prefix=dehya', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

**Comment by Linaqruf** [comment]
>config_util

did u check this option? 
![image](https://user-images.githubusercontent.com/50163983/222695808-c171ea70-63b8-4961-8c59-924dac2dcd5a.png)

I think it's better to not use that for a while until the bugs fixed, main repo did a massive changes so we can expect error.
https://github.com/kohya-ss/sd-scripts
![image](https://user-images.githubusercontent.com/50163983/222696215-64b70009-110c-4dcf-a535-45cb26a0e5c7.png)
