### ISSUE TITLE
Fast trainer "no metadata" error?

### ISSUE THREAD

**Issue by Atoli** [Linaqruf/kohya-trainer#112]
I decided to try the fast kohya trainer colab, but got a strange error:

`Traceback (most recent call last):
  File "/content/kohya-trainer/train_network.py", line 507, in <module>
    train(args)
  File "/content/kohya-trainer/train_network.py", line 69, in train
    train_dataset = FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 828, in __init__
    raise ValueError(f"no metadata / メタデータファイルがありません: {json_file_name}")
ValueError: no metadata / メタデータファイルがありません: /content/drive/MyDrive/training_dir/meta_lat.json
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya-trainer/train_network.py', '--output_name=OFF', '--pretrained_model_name_or_path=/content/pretrained_model/anything-v3-fp32-pruned.safetensors', '--vae=/content/vae/anime.vae.pt', '--train_data_dir=/content/drive/MyDrive/Goku', '--in_json=/content/drive/MyDrive/training_dir/meta_lat.json', '--output_dir=/content/drive/MyDrive/training_dir/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--unet_lr=0.0001', '--text_encoder_lr=5e-05', '--optimizer_type=AdamW8bit', '--learning_rate=2e-06', '--lr_scheduler=constant', '--lr_warmup_steps=250', '--dataset_repeats=10', '--resolution=512', '--lowram', '--noise_offset=0.1', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--train_batch_size=4', '--max_token_length=225', '--max_train_epochs=20', '--clip_skip=2', '--logging_dir=/content/training_dir/logs', '--log_prefix=OFF', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.
`
What could this "no metadata" error be about?

How might i fix it?
I certainly connected my drive and i am sure i put the folder name and path correct, but i keep running into this issue.

**Comment by Norian11** [comment]
Having the same issue since the new update with the 1-click kohya trainer and the dreambooth trainer lora using almost the default options, i suppose is a general issue, hope they could say how fix this

**Comment by Atoli** [comment]
I believe this is where the error is:

```
Status Legend:
(OK):download completed.
Skipping directory 5_Goku
2023-03-05 16:07:40.898578: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-05 16:07:41.951879: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-05 16:07:41.952017: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-05 16:07:41.952038: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
found 0 images.
```

I have no idea why, but the colab is skipping my training folder.

**Comment by okoklol1212** [comment]
I think I'm able to make it by 
1) changing the code  

if install_xformers:
    !pip install xformers==**0.0.17 triton==2.0.0
    !pip install torch==2.0.0
    !pip uninstall torchvision
    !pip install torchvision -f https://download.pytorch.org/whl/cu111/torch_stable.html**
   
2) **Make sure the image file in put in the training_dir folder** 
3) **enable Auto-captioning** 
  use_wd_tagger (checked)
  use_blip (checked)

**Comment by Linaqruf** [comment]
I'm sorry, I don't have any plans to continue the Fast Kohya Trainer project (for now).

1. The code is getting longer in one cell, and my device is not powerful enough to handle it, (I run most of things in small laptop), which is causing lag.

2. It's really hard to maintain the 1-click cell colab.

3. There is another good 1-click cell colab project maintained by HollowStrawBerry, which is integrated with Google Drive. It based on my notebook (?) so you may get the same experience, or even better.You can check it out here: https://github.com/hollowstrawberry/kohya-colab
