### ISSUE TITLE
Colab doesn't run due to a TypeError: Input must be callable

### ISSUE THREAD

**Issue by Chudjak** [Linaqruf/kohya-trainer#113]
`+-------------------------------+-------------------------------------------------------+
| Hyperparameter                | Value                                                 |
+-------------------------------+-------------------------------------------------------+
| v2                            | False                                                 |
| v_parameterization            | False                                                 |
| project_name                  | optionaltypohelpme                                    |
| pretrained_model_name_or_path | /content/pretrained_model/Animefull-final-pruned.ckpt |
| vae                           | /content/vae/stablediffusion.vae.pt                   |
| train_folder_directory        | /content/LoRA/train_data                              |
| reg_folder_directory          | /content/LoRA/reg_data                                |
| output_dir                    | /content/drive/MyDrive/LoRA/output                    |
| resume_path                   | False                                                 |
+-------------------------------+-------------------------------------------------------+
+--------------------------------+-------+
| Hyperparameter                 | Value |
+--------------------------------+-------+
| enable_bucket                  | True  |
| resolution                     | 1024  |
| min_bucket_reso                | 320   |
| max_bucket_reso                | 1280  |
| bucket_reso_steps              | 64    |
| bucket_no_upscale              | False |
| cache_latents                  | True  |
| flip_aug                       | False |
| caption_extension              | .txt  |
| caption_dropout_rate           | 0     |
| caption_dropout_every_n_epochs | 0     |
+--------------------------------+-------+
+-------------------+---------------+
| Hyperparameter    | Value         |
+-------------------+---------------+
| network_dim       | 128           |
| network_alpha     | 128           |
| network_module    | networks.lora |
| network_weight    | False         |
| optimizer_type    | AdamW8bit     |
| optimizer_args    | False         |
| unet_lr           | 5e-05         |
| text_encoder_lr   | 5e-05         |
| lr_scheduler      | constant      |
| lr_warmup_steps   | 0             |
| lr_scheduler_args | 1             |
+-------------------+---------------+
+-----------------------------+------------------------------+
| Hyperparameter              | Value                        |
+-----------------------------+------------------------------+
| prior_loss_weight           | 1.0                          |
| lowram                      | True                         |
| noise_offset                | 0                            |
| max_train_type              | max_train_epochs             |
| max_train_type_value        | 8                            |
| train_batch_size            | 6                            |
| mixed_precision             | fp16                         |
| save_precision              | fp16                         |
| save_n_epochs_type          | save_n_epoch_ratio           |
| save_n_epochs_type_value    | 3                            |
| save_model_as               | safetensors                  |
| max_token_length            | 225                          |
| clip_skip                   | 2                            |
| gradient_checkpointing      | False                        |
| gradient_accumulation_steps | 1                            |
| seed                        | -1                           |
| logging_dir                 | /content/LoRA/logs           |
| additional_argument         | --shuffle_caption --xformers |
+-----------------------------+------------------------------+
2023-03-04 04:07:12.553601: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-04 04:07:13.659478: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-04 04:07:13.659641: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-04 04:07:13.659666: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-04 04:07:17.825383: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-04 04:07:18.944904: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-04 04:07:18.945022: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-04 04:07:18.945044: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "train_network.py", line 20, in <module>
    import library.config_util as config_util
  File "/content/kohya-trainer/library/config_util.py", line 113, in <module>
    class ConfigSanitizer:
  File "/content/kohya-trainer/library/config_util.py", line 116, in ConfigSanitizer
    def __validate_and_convert_twodim(klass, value: Sequence) -> Tuple:
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 201, in __init__
    raise TypeError("Input must be callable")
TypeError: Input must be callable
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--output_name=optionaltypohelpme', '--pretrained_model_name_or_path=/content/pretrained_model/Animefull-final-pruned.ckpt', '--vae=/content/vae/stablediffusion.vae.pt', '--train_data_dir=/content/LoRA/train_data', '--reg_data_dir=/content/LoRA/reg_data', '--output_dir=/content/drive/MyDrive/LoRA/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--learning_rate=5e-05', '--unet_lr=5e-05', '--text_encoder_lr=5e-05', '--lr_scheduler=constant', '--enable_bucket', '--resolution=1024', '--cache_latents', '--bucket_reso_steps=64', '--min_bucket_reso=320', '--max_bucket_reso=1280', '--caption_extension=.txt', '--prior_loss_weight=1.0', '--lowram', '--train_batch_size=6', '--max_train_epochs=8', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--max_token_length=225', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/LoRA/logs', '--log_prefix=optionaltypohelpme', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.`
No clue what else to say except for the fact that the "unable to register" thing shows up for a lot of the steps.

**Comment by Chudjak** [comment]
wow github fucked up that formatting. Adding a picture.
![chrome_xhfQRmknIa](https://user-images.githubusercontent.com/122031986/222875047-b08f6faa-a399-434f-8f26-b679f0743b9e.png)

**Comment by GeneralAwareness** [comment]
If you did a clone forget it as this notebook is no longer compatible with Kohya.

**Comment by Linaqruf** [comment]
alright this is caused the new update can only be used in python 3.10, while colab is 3.8
i don't know what they're thinking after supporting 3.8 with `from typing import List` in `lora.py`
![image](https://user-images.githubusercontent.com/50163983/222942223-39706203-5f0d-4439-885d-9734822adf0a.png)

**Comment by GeneralAwareness** [comment]
Yep, that kills it. :(  Google will take forever to update to 3.10.

**Comment by Linaqruf** [comment]
This happened right after i finished new update for LoRA dreambooth, pain.
Welp, now i think now you can use latest sd-scripts update.

https://github.com/kohya-ss/sd-scripts/commit/dd39e5d94490d89b2617d154509e3bceb1cc4aa2

**Comment by GeneralAwareness** [comment]
I can't checkout - branch: dd39e5d94490d89b2617d154509e3bceb1cc4aa2

**Comment by Linaqruf** [comment]
no dont checkout, just tick clone sd-scripts, it already on latest commit.

**Comment by GeneralAwareness** [comment]
Ahhh, alright I see clone and I am thinking cloning Kohya scripts directly.

**Comment by Linaqruf** [comment]
another problem
![image](https://user-images.githubusercontent.com/50163983/222961887-dd1523c8-ed81-43cc-8be3-46d0c64a6a5c.png)

**Comment by GeneralAwareness** [comment]
My time ran out on colab, but a lot of these I ran into last night.  They are deep in the code.
