### ISSUE TITLE
<Signals.SIGKILL: 9>

### ISSUE THREAD

**Issue by Eliont** [Linaqruf/kohya-trainer#119]
Hello and good time of day.

Train cell crashes.

`[Dataset 0]
loading image sizes.
100% 302/302 [00:00<00:00, 1442687.71it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (768, 768), count: 3020
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--output_name=test', '--pretrained_model_name_or_path=/content/pretrained_model/model.ckpt', '--vae=/content/vae/anime.vae.pt', '--train_data_dir=/content/LoRA/train_data', '--in_json=/content/LoRA/meta_lat.json', '--output_dir=/content/drive/MyDrive/LoRA/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--learning_rate=1e-05', '--unet_lr=1e-05', '--text_encoder_lr=5e-06', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=1', '--dataset_repeats=10', '--resolution=768', '--lowram', '--noise_offset=0.1', '--train_batch_size=6', '--max_train_epochs=20', '--mixed_precision=fp16', '--save_precision=fp16', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--max_token_length=225', '--gradient_checkpointing', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/LoRA/logs', '--log_prefix=test', '--shuffle_caption', '--xformers']' died with <Signals.SIGKILL: 9>.`

**Comment by Linaqruf** [comment]
hi, i think your model is quiet big,

**Comment by Eliont** [comment]
It's basic NAI from https://huggingface.co/Tanzdiktator/SDModelsCollection/blob/main/model.ckpt 
Peoples recommend to train with it. 

But yeah, it's 7GB. So it not colab issue, i will try colab "animefull" version later, thanks fo responce.

**Comment by Linaqruf** [comment]
yeah, i suggest to use animefull, because it's pruned version.

**Comment by 0me1** [comment]
Hi, I tried to use full nai in the old colab and it worked but the new version doesn't work. Why is it like this ?

**Comment by minermanb** [comment]
Also getting this.
