### ISSUE TITLE
train_network.py: error: unrecognized arguments: /content/LoRA/config/config_file.toml

### ISSUE THREAD

**Issue by GeneralAwareness** [Linaqruf/kohya-trainer#120]
train_network.py: error: unrecognized arguments: /content/LoRA/config/config_file.toml
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by GeneralAwareness** [comment]
Fixed.

config_file = " /content/LoRA/config/config_file.toml" #@param {type:'string'}  That space was the issue.
