### ISSUE TITLE
How to fix this ? 

### ISSUE THREAD

**Issue by DervlexArt** [Linaqruf/kohya-trainer#126]
We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like /content/vae/stablediffusion.vae.pt is not the path to a directory containing a file named diffusion_pytorch_model.bin or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
retry with subfolder='vae'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/diffusers/modeling_utils.py", line 605, in _get_model_file
    model_file = hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/vae/stablediffusion.vae.pt'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

**Comment by Linaqruf** [comment]
which notebook is this?

**Comment by xcreateadmin** [comment]
> which notebook is this?

Getting same error in Kohya LoRA Dreambooth
