### ISSUE TITLE
Converting Output .ckpt to Diffusers gives error

### ISSUE THREAD

**Issue by xcreateadmin** [Linaqruf/kohya-trainer#143]
My training works fine, It also works on A1111 Web UI but to deploy it I want to convert .ckpt file to Hugging Face Diffusers.

I use this [ckpt to diffusers](https://huggingface.co/spaces/diffusers/sd-to-diffusers) which works for Fast-Dreambooth ckpt file but Kohya Lora Dreambooth Notebook's ckpt does not work with this. It doesn't provide any log just "ERROR":

https://huggingface.co/spaces/diffusers/sd-to-diffusers

The same error comes using .safetensors as well

I would really appreciate any suggestion I can get. Pretty Please.

https://drive.google.com/file/d/1LHThZCSPN5WQFu46zyQ5H7FwwmZ-exa2/view?usp=sharing

**Comment by Linaqruf** [comment]
Hi, I'm sorry I can't help much for converting LoRA to diffusers format. Because:
1. LoRA support in diffusers is based on Cloneofsimo's implementation, and not Kohya's
2. No official script to convert Kohya's LoRA to diffusers format

And this script https://huggingface.co/spaces/diffusers/sd-to-diffusers is only useful for converting full Stable Diffusion model to Diffusers format. But probably this repo can help you, https://github.com/haofanwang/Lora-for-Diffusers, unofficial and little tricky, by merging safetensors LoRA with diffusers format.

**Comment by xcreateadmin** [comment]
Thanks for the suggestions. [Lora-for-Diffusers]( https://github.com/haofanwang/Lora-for-Diffusers) do work but converted diffuser results are terrible. Completely out of place. 
But at the end of the day, all I need is to run inference using code for [kohya-Lora Dreambooth](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb) models.

The models I train using [Kohya-Lora-Dreambooth](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb) work on A111 Web UI but **6.3. Inference** gives the following error. 

```
2023-03-22 03:06:07.242878: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-22 03:06:07.969420: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-22 03:06:07.969529: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-22 03:06:07.969547: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
load Diffusers pretrained models
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/diffusers/configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 172, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/kohya-trainer/gen_img_diffusers.py", line 2790, in <module>
    main(args)
  File "/content/kohya-trainer/gen_img_diffusers.py", line 1932, in main
    loading_pipe = StableDiffusionPipeline.from_pretrained(args.ckpt, safety_checker=None, torch_dtype=dtype)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/pipeline_utils.py", line 454, in from_pretrained
    config_dict = cls.load_config(
  File "/usr/local/lib/python3.9/dist-packages/diffusers/configuration_utils.py", line 363, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like  is not the path to a directory containing a model_index.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```

I used all the default settings only but still **6.3. Inference** doesn't work

**Comment by Linaqruf** [comment]
Hi, I think you forgot to specify the model
![image](https://user-images.githubusercontent.com/50163983/226830293-4c013584-6766-41f3-9165-6a35b7a4e4d7.png)

**Comment by Linaqruf** [comment]
Also yeah, currently no official scripts to convert Kohya LoRA to diffusers format. I think we can ask for the feature in https://github.com/kohya-ss/sd-scripts/

**Comment by xcreateadmin** [comment]
> https://github.com/kohya-ss/sd-scripts/

Oh Yeah forgot it but now it gives a different error:

```
2023-03-22 15:13:04.952895: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-22 15:13:05.703594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-22 15:13:05.703718: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-22 15:13:05.703738: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "/content/kohya-trainer/gen_img_diffusers.py", line 2790, in <module>
    main(args)
  File "/content/kohya-trainer/gen_img_diffusers.py", line 1929, in main
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.ckpt)
  File "/content/kohya-trainer/library/model_util.py", line 877, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "/content/kohya-trainer/library/model_util.py", line 234, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
```
Using Kohya Lora Dreambooth, Google Colab

**Comment by xcreateadmin** [comment]
> Hi, I think you forgot to specify the model ![image](https://user-images.githubusercontent.com/50163983/226830293-4c013584-6766-41f3-9165-6a35b7a4e4d7.png)

Oh yes I forgot to add model, it works now.

One last question, is Lora Inference (txt2img) faster than SD Full Model Inference? Or is it the same?
