### ISSUE TITLE
died with <Signals.SIGKILL: 9> when starting to train

### ISSUE THREAD

**Issue by Rorutop** [Linaqruf/kohya-trainer#148]
Dont know why does this happen

```
[Dataset 0]
loading image sizes.
100% 499/499 [00:01<00:00, 494.73it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 704), count: 10
bucket 1: resolution (384, 640), count: 160
bucket 2: resolution (448, 576), count: 10
bucket 3: resolution (576, 448), count: 360
bucket 4: resolution (640, 384), count: 4450
mean ar error (without repeats): 0.10505583268482825
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--sample_prompts=/content/LoRA/config/sample_prompt.txt', '--dataset_config=/content/LoRA/config/dataset_config.toml', '--config_file=/content/LoRA/config/config_file.toml']' died with <Signals.SIGKILL: 9>.
```

**Comment by Linaqruf** [comment]
Hi, I think your selected pretrained model bigger than >5gb

**Comment by Rorutop** [comment]
But im using the Animefull-pruned from the default model, why does that happen??

**Comment by tommyjohn81** [comment]
usually a memory issue, try reducing your batch size to 1 and try again

**Comment by nickthelegend** [comment]
[tommyjohn81](https://github.com/tommyjohn81) thanks i fixed the issue

**Comment by sofoklis326** [comment]
i have same problem doing sd with lora, @nickthelegend did you reduce batch size to fix it ?

**Comment by le-khang** [comment]
I had the same error today and I asked Ashleyk on Discord. He told me it's probably an "Out of Memory" error and suggested trying to close all the other apps. Since I'm using Runpod, I just need to typed the command "fuser -k 3001/tcp" to kill SD. That brought down my GPU Memory Usage to 0%, and then I could go back to training like normal.
