### ISSUE TITLE
LoRA file does not work with A1111 Additional Networks

### ISSUE THREAD

**Issue by MitPitt** [Linaqruf/kohya-trainer#20]
The inference cell in your colab seems to work fine, but it doesn't seem to work in Automatic1111 colab with [sd-webui-additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks) extension installed.
When I try to load it up:
```
LoRA weight: 1, model: /content/last.safetensors
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 125, in process
    du_state_dict = load_file(model)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
Exception: Error while deserializing header: HeaderTooLarge
```

**Comment by MitPitt** [comment]
I set network_dim = 32, if that's relevant

**Comment by MitPitt** [comment]
nevermind i think it was because i was downloading it incorrectly, it works fine now
