### ISSUE TITLE
Vast.ai torch 1.13.1+cu116 issue

### ISSUE THREAD

**Issue by Desm0nt** [Linaqruf/kohya-trainer#23]
Impossible to run trainer on vast.ai on pytorch/pytorch_1.13.1-cuda116-cudnn8-runtime docker image with xformers-0.0.16rc397-cp310-cp310-manylinux2014_x86_64.whl from facebook (ubuntu-22.04-py3.10-torch1.13.1+cu117). With other prebuilded xformers (if manually install 1.12.1 + cuda116 and corresponding xformers) same story.

> Replace CrossAttention.forward to use xformers
prepare optimizer, data loader etc.
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
use 8-bit Adam optimizer
running training / 学習開始
  num examples / サンプル数: 7117
  num batches per epoch / 1epochのバッチ数: 7117
  num epochs / epoch数: 5
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 35000
steps:   0%|                                          | 0/35000 [00:00<?, ?it/s]epoch 1/5
Traceback (most recent call last):
  File "/workspace/kohya-trainer/fine_tune.py", line 1059, in <module>
    train(args)
  File "/workspace/kohya-trainer/fine_tune.py", line 624, in train
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1314, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 414, in wrapper
    outputs = fn(ctx, *args)
  File "/opt/conda/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 111, in backward
    grads = _memory_efficient_attention_backward(
  File "/opt/conda/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 381, in _memory_efficient_attention_backward
    grads = op.apply(ctx, inp, grad)
  File "/opt/conda/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 184, in apply
    (grad_q, grad_k, grad_v,) = cls.OPERATOR(
  File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
steps:   0%|                                          | 0/35000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'fine_tune.py', '--pretrained_model_name_or_path=/workspace/pre_trained_model/Anything-V3.ckpt', '--in_json', '/workspace/meta_lat.json', '--train_data_dir=/workspace/img', '--output_dir=/workspace/output', '--shuffle_caption', '--train_batch_size=1', '--learning_rate=2e-6', '--lr_scheduler=constant', '--max_token_length=225', '--clip_skip=2', '--mixed_precision=fp16', '--max_train_steps=35000', '--use_8bit_adam', '--xformers', '--gradient_checkpointing', '--gradient_accumulation_steps', '1', '--save_model_as=ckpt', '--save_state', '--save_every_n_epochs=1', '--logging_dir=/workspace/fine_tune/training_logs', '--log_prefix', 'fine-tune-style1']' returned non-zero exit status 1.

**Comment by Desm0nt** [comment]
Solved by using python 3.8 instead of 3.10.
