### ISSUE TITLE
Don't work in Colab since yesterday

### ISSUE THREAD

**Issue by Desm0nt** [Linaqruf/kohya-trainer#27]
Crashed on training step.
```
steps:   0% 0/10 [00:00<?, ?it/s]epoch 1/2
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'fine_tune.py', '--pretrained_model_name_or_path=/content/pre_trained_model/Anything-v4-5-pruned.ckpt', '--in_json', '/content/meta_lat.json', '--train_data_dir=/content/kohya-trainer/img', '--output_dir=/content/drive/MyDrive/fine_tune/output', '--shuffle_caption', '--train_batch_size=1', '--learning_rate=2e-6', '--lr_scheduler=constant', '--max_token_length=225', '--clip_skip=2', '--mixed_precision=fp16', '--dataset_repeats', '1', '--max_train_steps=10', '--use_8bit_adam', '--xformers', '--gradient_accumulation_steps', '1', '--save_model_as=ckpt', '--save_state', '--resume', '/content/drive/MyDrive/fine_tune/last-state', '--save_every_n_epochs=1', '--save_precision=float', '--logging_dir=/content/fine_tune/training_logs', '--log_prefix', 'fine-tune-style1']' died with <Signals.SIGKILL: 9>.````

**Comment by zundamon075** [comment]
Sad to say, but T4 always crashes!

**Comment by Linaqruf** [comment]
You can try the latest notebook changes, I added some patches.

**Comment by etherealxx** [comment]
i got the same error just now
