### ISSUE TITLE
Missing dependencies, cannot start training

### ISSUE THREAD

**Issue by hornedpariah** [Linaqruf/kohya-trainer#31]
cell 4.2: 
2023-01-23 19:54:33.000677: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-23 19:54:34.273687: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-01-23 19:54:34.273927: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-01-23 19:54:34.273957: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
downloading wd14 tagger model from hf_hub
/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py:982: FutureWarning: The `force_filename` parameter is deprecated as a new caching system, which keeps the filenames as they are on the Hub, is now in place.
  warnings.warn(
Downloading: 100% 328k/328k [00:00<00:00, 5.77MB/s]
Downloading: 100% 3.81M/3.81M [00:00<00:00, 15.7MB/s]
Downloading: 100% 174k/174k [00:00<00:00, 3.12MB/s]
Downloading: 100% 365M/365M [00:04<00:00, 90.2MB/s]
Downloading: 100% 13.8k/13.8k [00:00<00:00, 19.1MB/s]
found 1244 images.
loading model and labels
2023-01-23 19:54:43.276085: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
100% 1244/1244 [02:16<00:00,  9.14it/s]
done!

error on cell 5.2:

/content/kohya-trainer
+-------------------------------+----------------------------------------------------+
| Hyperparameter                | Value                                              |
+-------------------------------+----------------------------------------------------+
| v2                            | True                                               |
| v_parameterization            | False                                              |
| pretrained_model_name_or_path | /content/pre_trained_model/Anything-v4-pruned.ckpt |
| vae                           | False                                              |
| train_data_dir                | /content/fine_tune/train_data                      |
| in_json                       | /content/fine_tune/meta_lat.json                   |
| output_dir                    | /content/drive/MyDrive/fine_tune/output            |
| resume_path                   | False                                              |
| project_name                  | hito-komoru                                        |
| mixed_precision               | fp16                                               |
| save_precision                | fp16                                               |
| save_every_n_epochs           | 0                                                  |
| save_last_n_epochs            | 0                                                  |
| save_model_as                 | ckpt                                               |
| resolution                    | 512                                                |
| train_batch_size              | 1                                                  |
| max_token_length              | 225                                                |
| train_text_encoder            | False                                              |
| use_8bit_adam                 | True                                               |
| learning_rate                 | 2e-06                                              |
| dataset_repeats               | 1                                                  |
| max_train_steps               | 5000                                               |
| seed                          | 0                                                  |
| gradient_checkpointing        | False                                              |
| gradient_accumulation_steps   | 1                                                  |
| clip_skip                     | 2                                                  |
| logging_dir                   | /content/fine_tune/logs                            |
| log_prefix                    | hito-komoru                                        |
| additional_argument           | --save_state --shuffle_caption --xformers          |
+-------------------------------+----------------------------------------------------+
2023-01-23 20:09:37.571896: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-23 20:09:38.284900: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-23 20:09:38.285011: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-23 20:09:38.285033: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-23 20:09:41.168607: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-23 20:09:41.878917: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-23 20:09:41.879020: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-23 20:09:41.879038: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
update token length: 225
loading existing metadata: /content/fine_tune/meta_lat.json
Traceback (most recent call last):
  File "fine_tune.py", line 341, in <module>
    train(args)
  File "fine_tune.py", line 33, in train
    train_dataset = train_util.FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 592, in __init__
    assert len(abs_path) >= 1, f"no image / 画像がありません: {abs_path}"
AssertionError: no image / 画像がありません: []
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'fine_tune.py', '--v2', '--pretrained_model_name_or_path=/content/pre_trained_model/Anything-v4-pruned.ckpt', '--train_data_dir=/content/fine_tune/train_data', '--in_json=/content/fine_tune/meta_lat.json', '--output_dir=/content/drive/MyDrive/fine_tune/output', '--output_name=hito-komoru', '--mixed_precision=fp16', '--save_precision=fp16', '--save_model_as=ckpt', '--resolution=512', '--train_batch_size=1', '--max_token_length=225', '--use_8bit_adam', '--learning_rate=2e-06', '--dataset_repeats=1', '--max_train_steps=5000', '--gradient_accumulation_steps=1', '--logging_dir=/content/fine_tune/logs', '--log_prefix=hito-komoru', '--save_state', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

**Comment by Linaqruf** [comment]
there are several error here
1. `--v2` True but you're using Anything-V4 as pretrained model which is SDV1 model
2. you need to redefine where your train data/dataset located because no image found in `/content/fine_tune/train_data`

**Comment by hornedpariah** [comment]
the first time i copied the path from my drive into cell 3.1 as "/content/drive/MyDrive/payload/datasets/Art"

i moved it to the notebook and noticed i needed to update some spots. Its running now although i get that tensorflow error

**Comment by Linaqruf** [comment]
tensorflow error is fine

**Comment by hornedpariah** [comment]
so on 4.2 Data Annotation :
/content/kohya-trainer/finetune
2023-01-25 21:34:10.652769: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-25 21:34:11.324505: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-01-25 21:34:11.324631: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-01-25 21:34:11.324650: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
found 1247 images.
loading model and labels
2023-01-25 21:34:13.751141: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
100% 1247/1247 [01:58<00:00, 10.57it/s]
done!

this is ok?

**Comment by Linaqruf** [comment]
yes, you're good
