### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x09'

### ISSUE THREAD

**Issue by TsGrolken** [Linaqruf/kohya-trainer#32]
Hi, I am using my own dataset on Colab by uploading 2 .png file manually to the /content/fine_tune/train_data, and get following error for 4.4. Aspect Ratio Bucketing and Cache Latents:

found 12 images.
loading existing metadata: /content/fine_tune/meta_clean.json
load VAE: /content/pre_trained_model/Anything-v3-pruned.ckpt
Traceback (most recent call last):
  File "prepare_buckets_latents.py", line 179, in <module>
    main(args)
  File "prepare_buckets_latents.py", line 57, in main
    vae = model_util.load_vae(args.model_name_or_path, weight_dtype)
  File "/usr/local/lib/python3.8/dist-packages/library/model_util.py", line 1112, in load_vae
    else torch.load(vae_id, map_location="cuda"))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x09'.

**Comment by Linaqruf** [comment]
hello, this is happened because aria2c can't get filename when downloading from huggingface, and also i forgot to create conditional if-else to load certain model extensions instead of naming all of them as .ckpt

already fixed for 3 colab, please dont use dreambooth colab because i haven't touch it for 5 days.
