### ISSUE TITLE
Error when start training

### ISSUE THREAD

**Issue by suryacandra** [Linaqruf/kohya-trainer#35]
full logs
```
2023-01-25 03:52:04.298041: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-25 03:52:05.003275: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-25 03:52:05.003421: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-25 03:52:05.003441: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-25 03:52:07.885109: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-25 03:52:08.539696: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-25 03:52:08.539797: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-01-25 03:52:08.539816: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
Downloading: 100% 961k/961k [00:00<00:00, 2.60MB/s]
Downloading: 100% 525k/525k [00:00<00:00, 1.70MB/s]
Downloading: 100% 389/389 [00:00<00:00, 543kB/s]
Downloading: 100% 905/905 [00:00<00:00, 1.14MB/s]
update token length: 225
Use DreamBooth method.
prepare train images.
found directory 5_masabodo illustration contains 139 image files
695 train images with repeating.
prepare reg images.
found directory 1_illustration contains 0 image files
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
loading image sizes.
100% 139/139 [00:00<00:00, 12514.67it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (256, 832), count: 0
bucket 1: resolution (256, 896), count: 0
bucket 2: resolution (256, 960), count: 0
bucket 3: resolution (256, 1024), count: 0
bucket 4: resolution (320, 704), count: 5
bucket 5: resolution (320, 768), count: 0
bucket 6: resolution (384, 640), count: 345
bucket 7: resolution (448, 576), count: 150
bucket 8: resolution (512, 512), count: 160
bucket 9: resolution (576, 448), count: 35
bucket 10: resolution (640, 384), count: 0
bucket 11: resolution (704, 320), count: 0
bucket 12: resolution (768, 320), count: 0
bucket 13: resolution (832, 256), count: 0
bucket 14: resolution (896, 256), count: 0
bucket 15: resolution (960, 256), count: 0
bucket 16: resolution (1024, 256), count: 0
mean ar error (without repeats): 0.05949234465711338
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "train_network.py", line 424, in <module>
    train(args)
  File "train_network.py", line 64, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "/content/kohya-trainer/library/train_util.py", line 1222, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "/content/kohya-trainer/library/model_util.py", line 869, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/kohya-trainer/library/model_util.py", line 846, in load_checkpoint_with_text_encoder_conversion
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x09'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--network_dim=128', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--pretrained_model_name_or_path=/content/pre_trained_model/Anything-v3-pruned.ckpt', '--vae=/content/vae/anime.vae.pt', '--caption_extension=.txt', '--train_data_dir=/content/dreambooth/train_illustration', '--reg_data_dir=/content/dreambooth/reg_illustration', '--output_dir=/content/dreambooth/output', '--enable_bucket', '--prior_loss_weight=1.0', '--output_name=masabodo', '--mixed_precision=fp16', '--save_precision=fp16', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--resolution=512', '--cache_latents', '--train_batch_size=1', '--max_token_length=225', '--use_8bit_adam', '--learning_rate=0.0001', '--max_train_epochs=5', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/fine_tune/logs', '--log_prefix=masabodo', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.
```

**Comment by Linaqruf** [comment]
hello, if you;'re using dreambooth please dont use colab ram patch

**Comment by Aikin-Ai** [comment]
> hello, if you;'re using dreambooth please dont use colab ram patch

I have exactly the same error while trying to train LoRA. Colab ram patch is disabled.

**Comment by suryacandra** [comment]
> > hello, if you;'re using dreambooth please dont use colab ram patch
> 
> I have exactly the same error while trying to train LoRA. Colab ram patch is disabled.



> > hello, if you;'re using dreambooth please dont use colab ram patch
> 
> I have exactly the same error while trying to train LoRA. Colab ram patch is disabled.

same and still error

**Comment by Linaqruf** [comment]
hello, this is happened because aria2c can't get filename when downloading from huggingface, and also i forgot to create conditional if-else to load certain model extensions instead of naming all of them as .ckpt

already fixed for 3 colab, please use updateed colab instead of copied one,

also please dont use native reambooth colab before i fixed it because i haven't touch it for 5 days.
