### ISSUE TITLE
Assertion Error when trying to train (Kohya trainer not lora)

### ISSUE THREAD

**Issue by AnANTKA** [Linaqruf/kohya-trainer#68]
I get this error when trying to train.

2023-02-08 16:17:25.037017: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-08 16:17:26.206157: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-08 16:17:26.206349: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-08 16:17:26.206379: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-08 16:17:29.628318: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-08 16:17:30.293424: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-08 16:17:30.293541: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-08 16:17:30.293561: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 30.3MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 21.3MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 187kB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 412kB/s]
update token length: 225
loading existing metadata: /content/fine_tune/meta_lat.json
Traceback (most recent call last):
  File "fine_tune.py", line 343, in <module>
    train(args)
  File "fine_tune.py", line 33, in train
    train_dataset = train_util.FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 646, in __init__
    assert len(abs_path) >= 1, f"no image / 画像がありません: {image_key}"
AssertionError: no image / 画像がありません: miwanoragu-(1)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'fine_tune.py', '--pretrained_model_name_or_path=/content/pre_trained_model/Anything-v3-1.safetensors', '--vae=/content/vae/anime.vae.pt', '--train_data_dir=/content/fine_tune/train_data', '--in_json=/content/fine_tune/meta_lat.json', '--output_dir=/content/drive/MyDrive/fine_tune/output', '--output_name=MiwanoRaguPixiv', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=1', '--save_model_as=safetensors', '--resolution=512', '--train_batch_size=1', '--max_token_length=225', '--use_8bit_adam', '--learning_rate=2e-06', '--dataset_repeats=1', '--max_train_steps=5000', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/fine_tune/logs', '--log_prefix=MiwanoRaguPixiv', '--save_state', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

Any help would be very appreciated

**Comment by AnANTKA** [comment]
I realised that the train data directory was wrong. I feel stupid now lol.
