### ISSUE TITLE
Fresh install errors

### ISSUE THREAD

**Issue by DrGunnarMallon** [Linaqruf/kohya-trainer#94]
Hi,
I've just installed Kohya to generate some LORA. However, even leaving all at default (besides the folders), I get the following error:

```
import network module: networks.lora
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "X:\Stable Diffusion\Kohya\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "X:\Stable Diffusion\Kohya\kohya_ss\train_network.py", line 150, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "X:\Stable Diffusion\Kohya\kohya_ss\library\train_util.py", line 1536, in get_optimizer
    assert optimizer_type is None or optimizer_type == "", "both option use_8bit_adam and optimizer_type are specified / use_8bit_adamとoptimizer_typeの両方 のオプションが指定されています"
AssertionError: both option use_8bit_adam and optimizer_type are specified / use_8bit_adamとoptimizer_typeの両方のオプションが指定されています
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "X:\Stable Diffusion\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "X:\Stable Diffusion\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "X:\Stable Diffusion\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "X:\Stable Diffusion\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['X:\\Stable Diffusion\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=X:/Art/LoraTrainingData/realisticVisionV13_v13.safetensors', '--train_data_dir=X:/Art/LoraTrainingData/myStyle/image', '--resolution=512,512', '--output_dir=X:/Art/LoraTrainingData/myStyle/model', '--logging_dir=X:/Art/LoraTrainingData/myStyle/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=170', '--train_batch_size=1', '--max_train_steps=1700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--optimizer_type=AdamW', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.
```

Any help would be greatly appreciated. It appears to have an issue with the optimizer and adam8b being select. When I unselect use_adam8bit I run out of mem (8GB 3080) and I don't see an option to select None for optimizer.

Thanks :)

**Comment by Linaqruf** [comment]
Hi! I think you're asking in the wrong repo. I guess you're using [bmaltais's GUI](https://github.com/bmaltais/kohya_ss)?
But I will try my best to give answer.

The problem is, you can't set both `--use_8bit_adam` and `--optimizer_type` at the same time. You should remove one of them, I suggest to set `--optimizer_type` to `AdamW8bit`, that's the same as `--use_8bit_adam.

**Comment by DrGunnarMallon** [comment]
Hey - thank you so much and my bad :)
