### ISSUE TITLE
What I'm doing wrong?

### ISSUE THREAD

**Issue by Gvaroo** [Linaqruf/kohya-trainer#99]
`+-------------------------------+-----------------------------------------------------+
| Hyperparameter                | Value                                               |
+-------------------------------+-----------------------------------------------------+
| v2                            | False                                               |
| v_parameterization            | False                                               |
| project_name                  | modernia                                            |
| pretrained_model_name_or_path | /content/pretrained_model/Anything-v3-1.safetensors |
| vae                           | /content/vae/waifudiffusion.vae.pt                  |
| train_data_dir                | /content/LoRA/train_data                            |
| in_json                       | /content/LoRA/meta_lat.json                         |
| output_dir                    | /content/drive/MyDrive/LoRA/output                  |
| resume_path                   | False                                               |
+-------------------------------+-----------------------------------------------------+
+--------------------------------+-------+
| Hyperparameter                 | Value |
+--------------------------------+-------+
| dataset_repeats                | 6     |
| resolution                     | 1024  |
| caption_dropout_rate           | 0     |
| tag_dropout_rate               | 0     |
| caption_dropout_every_n_epochs | 0     |
+--------------------------------+-------+
+-------------------+----------------------+
| Hyperparameter    | Value                |
+-------------------+----------------------+
| network_dim       | 32                   |
| network_alpha     | 32.0                 |
| network_module    | networks.lora        |
| network_weight    | False                |
| optimizer_type    | AdamW8bit            |
| optimizer_args    | False                |
| unet_lr           | 0.0001               |
| text_encoder_lr   | 1e-05                |
| lr_scheduler      | cosine_with_restarts |
| lr_warmup_steps   | 0                    |
| lr_scheduler_args | 1                    |
+-------------------+----------------------+
+-----------------------------+------------------------------+
| Hyperparameter              | Value                        |
+-----------------------------+------------------------------+
| lowram                      | True                         |
| noise_offset                | 0.1                          |
| max_train_type              | max_train_epochs             |
| max_train_type_value        | 6                            |
| train_batch_size            | 1                            |
| mixed_precision             | fp16                         |
| save_precision              | fp16                         |
| save_n_epochs_type          | save_n_epoch_ratio           |
| save_n_epochs_type_value    | 3                            |
| save_model_as               | safetensors                  |
| max_token_length            | 225                          |
| clip_skip                   | 2                            |
| gradient_checkpointing      | False                        |
| gradient_accumulation_steps | 1                            |
| seed                        | 1337                         |
| logging_dir                 | /content/LoRA/logs           |
| additional_argument         | --shuffle_caption --xformers |
+-----------------------------+------------------------------+
2023-02-25 12:57:03.590841: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-25 12:57:04.542946: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-25 12:57:04.543049: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-25 12:57:04.543068: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-25 12:57:08.013796: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-25 12:57:08.650998: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-25 12:57:08.651125: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-25 12:57:08.651148: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
usage: train_network.py
       [-h]
       [--v2]
       [--v_parameterization]
       [--pretrained_model_name_or_path PRETRAINED_MODEL_NAME_OR_PATH]
       [--train_data_dir TRAIN_DATA_DIR]
       [--shuffle_caption]
       [--caption_extension CAPTION_EXTENSION]
       [--caption_extention CAPTION_EXTENTION]
       [--keep_tokens KEEP_TOKENS]
       [--color_aug]
       [--flip_aug]
       [--face_crop_aug_range FACE_CROP_AUG_RANGE]
       [--random_crop]
       [--debug_dataset]
       [--resolution RESOLUTION]
       [--cache_latents]
       [--enable_bucket]
       [--min_bucket_reso MIN_BUCKET_RESO]
       [--max_bucket_reso MAX_BUCKET_RESO]
       [--bucket_reso_steps BUCKET_RESO_STEPS]
       [--bucket_no_upscale]
       [--caption_dropout_rate CAPTION_DROPOUT_RATE]
       [--caption_dropout_every_n_epochs CAPTION_DROPOUT_EVERY_N_EPOCHS]
       [--caption_tag_dropout_rate CAPTION_TAG_DROPOUT_RATE]
       [--reg_data_dir REG_DATA_DIR]
       [--in_json IN_JSON]
       [--dataset_repeats DATASET_REPEATS]
       [--output_dir OUTPUT_DIR]
       [--output_name OUTPUT_NAME]
       [--save_precision {None,float,fp16,bf16}]
       [--save_every_n_epochs SAVE_EVERY_N_EPOCHS]
       [--save_n_epoch_ratio SAVE_N_EPOCH_RATIO]
       [--save_last_n_epochs SAVE_LAST_N_EPOCHS]
       [--save_last_n_epochs_state SAVE_LAST_N_EPOCHS_STATE]
       [--save_state]
       [--resume RESUME]
       [--train_batch_size TRAIN_BATCH_SIZE]
       [--max_token_length {None,150,225}]
       [--mem_eff_attn]
       [--xformers]
       [--vae VAE]
       [--max_train_steps MAX_TRAIN_STEPS]
       [--max_train_epochs MAX_TRAIN_EPOCHS]
       [--max_data_loader_n_workers MAX_DATA_LOADER_N_WORKERS]
       [--persistent_data_loader_workers]
       [--seed SEED]
       [--gradient_checkpointing]
       [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
       [--mixed_precision {no,fp16,bf16}]
       [--full_fp16]
       [--clip_skip CLIP_SKIP]
       [--logging_dir LOGGING_DIR]
       [--log_prefix LOG_PREFIX]
       [--noise_offset NOISE_OFFSET]
       [--lowram]
       [--prior_loss_weight PRIOR_LOSS_WEIGHT]
       [--optimizer_type OPTIMIZER_TYPE]
       [--use_8bit_adam]
       [--use_lion_optimizer]
       [--learning_rate LEARNING_RATE]
       [--max_grad_norm MAX_GRAD_NORM]
       [--optimizer_args [OPTIMIZER_ARGS [OPTIMIZER_ARGS ...]]]
       [--lr_scheduler LR_SCHEDULER]
       [--lr_warmup_steps LR_WARMUP_STEPS]
       [--lr_scheduler_num_cycles LR_SCHEDULER_NUM_CYCLES]
       [--lr_scheduler_power LR_SCHEDULER_POWER]
       [--no_metadata]
       [--save_model_as {None,ckpt,pt,safetensors}]
       [--unet_lr UNET_LR]
       [--text_encoder_lr TEXT_ENCODER_LR]
       [--network_weights NETWORK_WEIGHTS]
       [--network_module NETWORK_MODULE]
       [--network_dim NETWORK_DIM]
       [--network_alpha NETWORK_ALPHA]
       [--network_args [NETWORK_ARGS [NETWORK_ARGS ...]]]
       [--network_train_unet_only]
       [--network_train_text_encoder_only]
       [--training_comment TRAINING_COMMENT]
train_network.py: error: unrecognized arguments: --lr_scheduler_num_cycles1
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--output_name=modernia', '--pretrained_model_name_or_path=/content/pretrained_model/Anything-v3-1.safetensors', '--vae=/content/vae/waifudiffusion.vae.pt', '--train_data_dir=/content/LoRA/train_data', '--in_json=/content/LoRA/meta_lat.json', '--output_dir=/content/drive/MyDrive/LoRA/output', '--network_dim=32', '--network_alpha=32.0', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--learning_rate=0.0001', '--unet_lr=0.0001', '--text_encoder_lr=1e-05', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles1', '--dataset_repeats=6', '--resolution=1024', '--keep_tokens=1', '--lowram', '--noise_offset=0.1', '--train_batch_size=1', '--max_train_epochs=6', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--max_token_length=225', '--seed=1337', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/LoRA/logs', '--log_prefix=modernia', '--shuffle_caption', '--xformers']' returned non-zero exit status 2.`

**Comment by Linaqruf** [comment]
No, my bad, it's actually my fault
Forgot to add `=`. Already fixed it. 
![image](https://user-images.githubusercontent.com/50163983/221362387-5838a37d-b2b3-46ea-ba26-55f0d89c1fd0.png)
